name: coiled-examples
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dask
  - dask-ml
  - coiled
  - pyarrow
  - s3fs
  - matplotlib
  - ipykernel
  - dask-labextension
  - xgboost
  - pandas=2
  - optuna
  - xarray
  - geogif
  - zarr
  - h5netcdf
  - pre-commit
  - earthaccess
